spring.datasource.url=jdbc:postgresql://dpg-d7jr4a0sfn5c73fvm6j0-a.oregon-postgres.render.com:5432/monitoring_db_zppx
spring.datasource.username=monitoring_db_zppx_user
spring.datasource.password=3HZeKHZ3j0yI5ozvIZUSwJF1dJXW9q5s

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.application.name=monitoring-system